# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  timeout: 5000  

development:
  <<: *default
  database: waijiao_development

production:
  <<: *default
  database: waijiao_production

test:
  <<: *default
  database: waijiao_test
